### ISSUE TITLE
Should we have common conda/pip requirements for the entire system test?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/system-test#109]
Should we have  common requirements for all of the system test so that any notebook could be run?  Currently we have pip and conda requirements at the lowest directory level.

Sounds like @Bobfrat is in favor, and I *think* I'm in favor also.

**Comment by ocefpaf** [comment]
Closing this.  The [ioos environment file](https://github.com/ioos/conda-recipes/blob/master/environment.yml) should take care of this.
