### ISSUE TITLE
Copy binstar packages from rsignell to ioos

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/system-test#196]
It's silly to have the ioos system-test binstar packages at rsignell instead of at ioos.    @srossross, can you please copy everything from binstar/rsignell to binstar/ioos?

**Comment by ocefpaf** [comment]
@jkupiec Rich and I implement a system using [travis-ci](https://travis-ci.org/ioos/conda-recipes) and [AppVeyor](https://ci.appveyor.com/project/ocefpaf/conda-recipes) that builds and uploads the packages in [IOOS/conda-recipes](https://github.com/ioos/conda-recipes).  The builds are working  for Linux and windows, MacOS will be available [soon](http://docs.travis-ci.com/user/multi-os/).

PRs to https://github.com/ioos/conda-recipes will trigger a new build, but the upload only occurs when the PR is merged.  The packages are hosted in the IOOS binstar channel,

https://binstar.org/IOOS/

I just tested the following commands (on Linux):

```bash
conda config --add channels ioos -f 

cat >req.txt <<EOL
iris
pyoos
pandas
folium
rdflib
geojson
requests
prettyplotlib
ipython-notebook
libnetcdf=4.2.1.1=1 
EOL

ENV_NAME=system-test
conda create --yes -n $ENV_NAME --file req.txt python=2.7
source activate system-test
```

This creates a conda virtual environment that is able to run all the notebooks in system-test.

PS: Make sure that ioos is the only channel in your `.condarc`, or other package version might get installed.
