### ISSUE TITLE
Merge outstanding pull requests

### ISSUE THREAD

**Issue by dpsnowden** [ioos/system-test#198]
All, there are 7 outstanding pull requests.  Can you please decide a way to divide the work and get these new results merged?  We're trying to write up some results and need to be able to see the latest and greatest. It looks like many of the PRs fail the travis-ci checks so I'm not sure what is involved.

@Bobfrat @birdage @kwilcox @kknee @ocefpaf @wckoeppen 

Anyone?....Bueller?

**Comment by ocefpaf** [comment]
There are no outstanding PR.  (I closed #173 today.)
