### ISSUE TITLE
Need a Wave Height Skill Assessment example for Nov 1-2, 2014

### ISSUE THREAD

**Issue by ocefpaf** [ioos/system-test#209]
.. with the "Underprediction of wave heights during Nov 1-2, 2014 along the East Coast" example.

**Comment by rsignell-usgs** [comment]
Inspired by talk by Joe Seinkeiwicz, Director or Ocean Prediction Center/NOAA/NWS/NCEP at the IOOS Coastal Ocean Modeling Testbed meeting, July 30, 2015 at SURA in DC.

**Comment by kknee** [comment]
awesome idea!  looking forward to seeing this!

**Comment by ocefpaf** [comment]
Moved this to https://github.com/ioos/notebooks_demos/issues/241
