### ISSUE TITLE
System-test website

### ISSUE THREAD

**Issue by ocefpaf** [ioos/system-test#212]
@dpsnowden 

I just pushed the webpage to [https://ioos.github.io/system-test/](https://ioos.github.io/system-test/). I will keep adding the notebooks in the next days.

Two quick questions:

- [X] Do you want a specific `GOOGLE_ANALYTICS` number to track visits?
- [X] Should we create an IOOS [disqus](https://disqus.com/) and add a `DISQUS_SITENAME` for comments?

**Comment by rsignell-usgs** [comment]
@ocefpaf , looks awesome!
Is something cool supposed to happen when we click the stations on the Folium plot at the end?

**Comment by ocefpaf** [comment]
> Is something cool supposed to happen when we click the stations on the Folium plot at the end?

The popup will show the data sources only, but if you click on the top right icon you can activate the HFRadar layer.

Note that the original [notebook](http://nbviewer.ipython.org/github/ioos/system-test/blob/master/Theme_2_Extreme_Events/Scenario_2B/HF_Radar_Currents/HF_Radar_Currents_west_coast.ipynb) is long and has no explanations about what is going on there.

I want to re-write the next notebooks into smaller chunks and add a "story" to them.

**Comment by rsignell-usgs** [comment]
Aha!  I see the HFRadar layer now.
It would be nice to have a color legend on that so we have an idea of wind speed (since wind magnitude on this plot is indicated by color, not length of arrow). 

Could you also have the time series pop up when you click a station, like you do with inundation and water temp?

-Rich

**Comment by ocefpaf** [comment]
Those are all good (and doable) suggestions.  But I think it is best to do this in a new notebook.   Right now  I want the notebooks to be as close as possible to their system-test repo counterparts.  I am only updating and cleaning them to make sure they will run.

**Comment by rsignell-usgs** [comment]
okay, got it.

**Comment by ocefpaf** [comment]
This notebook was re-written as a post and the test page is gone.  For the current page go to:
https://ioos.github.io/system-test/

**Comment by emiliom** [comment]
Very cool, @ocefpaf! I hadn't seen this Pelicanized/bloggified version of the system-test notebooks! The posts look great, and it's nice to see the links to the original notebooks and mybinder. BTW, the mybinder link goes to an index notebook, not to the individual notebook. I think it'd be more user friendly if it went straight to the notebook presented on the blog post; but obviously I have no clue if that's possible with mybinder ...

**Comment by ocefpaf** [comment]
> I think it'd be more user friendly if it went straight to the notebook presented on the blog post

It is probably possible.  I will look into that.

**Comment by ocefpaf** [comment]
@emiliom Disqus should be online.  Let me know if it works for you.
